### PR TITLE
Adds new funky viro mask to vendors

### PR DESCRIPTION
**Pull request by FargothUr**
## About The Pull Request

This is part of my project to add new things to each department's vendor
Capture

## Why It's Good For The Game

Virologists actually get something cool for hacking their vendor

## Changelog
:cl:
add: Cool virology mask
/:cl:

### CODE REVIEW

**Comment by Wrim1r** [comment]
Take a picture and put it in the PR, you goober.

**Comment by coldud13** [comment]
there's the sprites in the checks, under the icon diff bot. but yes, some pictures of it in game would be real nice

**Comment by FargothUr** [comment]
just provided some screenshots, updated the DMI file too

**Comment by coldud13** [comment]
this isn't actually in the viro clothing vendor from what i can tell, everything else looks good tho

**Comment by FargothUr** [comment]
should be now

**Pull request merged**
