### PR TITLE
Button fixes and Permabrig Overhaul

### PR DESCRIPTION
**Pull request by MrFagetti**
fcsa

## About The Pull Request

Makes changes to table-buttons, RD's office has them on a wall and bridge has a better both sides design. Additionally, Perma is now massively changed, hopefully for the better, removing all the dumb stuff and making the place more overall condensed and less hotel-ish.

## Why It's Good For The Game

Enforces better gameplay from prisoners (long shot, but one can dream). On the subject of buttons, RD now can access his gay little buttons and Bridge can be secured better, plus the Captain can now reach his authenticator.

## Changelog
:cl:
add: brig freezer to kitchen, prisoners will have to ask for access from Security or Warden
tweak: Overall Perma is now more condensed and easier to navigate
tweak: buttons that were once on tables are now accessible here and there. ( I may have missed a few)
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
rather than having to map all the fixes, just revert the change citadel did.

**Comment by MrFagetti** [comment]
> rather than having to map all the fixes, just revert the change citadel did. (referring to buttons)

Because this PR is not just a button fix, but also a large overhaul to Brig.

**Comment by jjpark-kb** [comment]
I think my only issue with this is I don't see the replacement of the late join markers.

**Comment by coldud13** [comment]
is this ready?

**Comment by MrFagetti** [comment]
This one is ready

**Pull request merged**
