### PR TITLE
Removes Dogborgs and Fixes Chef Access to Morgue

### PR DESCRIPTION
**Pull request by MrBobCool**
## About The Pull Request

Readds morgue access because skyrat thought it'd be a good idea to remove it hello??

Deletes ability to become a dogborg module, and removed the entire module itself. 

## Why It's Good For The Game

The chef needs his meat one way or another.
Dogborgs are cringe.

## Changelog
:cl:
code: changed some code
delet: dogborg code
removed: dogborgs
/:cl:

### CODE REVIEW

**Comment by Wrim1r** [comment]
Dragon cyborgs are pretty based though??? Remove player controlled mobs from being able to be ERPed and restrict the menu to the human class instead of removing things, honestly.

Also, I agree with the chef change, but make a separate PR and don't make changes directly on your master branch, you radical dude.

**Comment by MrBobCool** [comment]
> Dragon cyborgs are pretty based though??? Remove player controlled mobs from being able to be ERPed and restrict the menu to the human class instead of removing things, honestly. In addition, you should comment out code instead of deleting it in order to avoid any issues associated with Lumos being a Skyrat downstream.
> 
> Also, I agree with the chef change, but make a separate PR and don't make changes directly on your master branch, you radical dude.

Drakeborgs were not actually dragon cyborgs, they were just another version of dogborgs that were named drake for some odd reason. I am just removing dogborgs and adding the chef's access back, not messing with the ei are pee code. We are a downstream, comments shouldn't matter and if it turns out to be a very mattersome topic then maybe I'll do so.
As for the separate pr for chef, couldn't really find out how to make a separate one. It isn't a big change but if Coldud tells me to remove it I will.

**Comment by coldud13** [comment]
ok epic pr. but pls comment things out instead of deleting it and split the chef access into another pr cause it's unatomic af

**Comment by MrBobCool** [comment]
> ok epic pr. but pls comment things out instead of deleting it and split the chef access into another pr cause it's unatomic af
> 
> oh also mark the commented out stuff with lumos change

right, I'll try and get to that

**Pull request closed without merging**
