### PR TITLE
Basement + Engineering v2 for snaxi

### PR DESCRIPTION
**Pull request by quackjack**
## About The Pull Request
Fleshes out the service basement and the area nearby, as well as moving a couple of rooms in engi around. Kitchen also gets the cold room basement treatment.
## Why It's Good For The Game
Takes engineering and service players off suicide watch when the map is selected
## Changelog
:cl:
add: Added more maint to the service basement, and a cold room on the same level that is connected
add: Added proper secure construction room and break room
/:cl:

### CODE REVIEW

**Comment by coldud13** [comment]
boxstation conflict, lemme fix this

**Comment by coldud13** [comment]
also it should've been in its own PR in the first place aaaaaaaaaa

**Comment by MrFagetti** [comment]
Is this ready to be merged?

**Comment by quackjack** [comment]
Yeah, I'm done with the pr now, lets get it merged

**Pull request merged**
