### PR TITLE
add piss to reagent list (unobtainable as of now)

### PR DESCRIPTION
**Pull request by fromgoman**
piss
2x toxin power as plasma (plasma is 3 and piss is 6)
has same effect of brain hurting juice (gain a trauma)

### CODE REVIEW

**Comment by fromgoman** [comment]
piss reagent

**Comment by MrFagetti** [comment]
image

**Comment by fromgoman** [comment]
piss reagemnt

**Comment by MrFagetti** [comment]
Make filling jars with it a throwable. Please for the meme, also even though we're effectively cut off move it to the modular bb

**Comment by fromgoman** [comment]
> Make filling jars with it a throwable. Please for the meme, also even though we're effectively cut off move it to the modular bb

piss regaent

**Comment by coldud13** [comment]
no

**Pull request closed without merging**
