### PR TITLE
Update the metastation bar area

### PR DESCRIPTION
**Pull request by frontline03**
## About The Pull Request

Moves the kitchen and hydroponics to a different area
image

## Why It's Good For The Game

Moves botany next to the kitchen making it easier for the bar to access botany and vice versa. Also is easier to access food made by botanists in the bar area

## Changelog
:cl:
Moved: Location of Kitchen
Moved: Location of Botany
Moved: Location of Service Lathe
Moved: Arcade machines
Added: Nutrimax and seed vendor to public garden
Removed: Diner area
/:cl:

### CODE REVIEW

**Comment by frontline03** [comment]
image

**Comment by frontline03** [comment]
The undoing changes commit does not mean it is undoing any changes, I just forgot to rename the damn thing

**Comment by MrFagetti** [comment]
Personally I would try and make the Service Hall easier to access as in you r current build. You're making a fairly sizable change for the layout, why not try to make things easier for people?

**Comment by frontline03** [comment]
Only way I could do that would be if I reworked the entirety of the bar area. I want to see if people like the first changes to botany and hydro, if they do, I'll start working on the rest of the bar area, including the lathe

**Comment by Wrim1r** [comment]
Current Issues:
- The kitchen does not have wiring.
- The kitchen backroom does not have its own APC and it's missing lights.
- The disposals system does not work properly
- Starboard maint APC is blocked by a door
- There is a stray service hall APC in the bar
- Random objects like fire extinguishers under doors
- Service Hall has no air alarm
- Missing lights in the bar and botany area
- Scrubber and distro pipes under walls is a big issue for engineers
- The waste line for botany's back room links to an independent waste line meant for the turbine
- Multiple distro pipes unattached to the main distro line
- Power cables under walls (God help us)
- There's a floating table from old botany in space east of the atmos turbine

I'm sure there's more, but that's what I found by looking at the map. The bar and kitchen lost their unique layout, but that's going into nitpicking. I don't think changes to Meta's previous layout are needed at all and players are already complaining about them in OOC.

**Comment by frontline03** [comment]
Fixing now

**Comment by frontline03** [comment]
Wait, regarding the APC, are you referring to the APC in the bottom left?

**Comment by frontline03** [comment]
The stray service hall APC was already fixed however.

**Comment by coldud13** [comment]
missing pipe


really bland and empty space



missing wires



old decal


window spawners are stacked up twice and this here is really messy



missing firelocks



hydro apc isnt wired



botany has a single fire alarm



wire goes into a wall in botany maint

image
disposals isnt connected and double wide walls are ugly

**Comment by quackjack** [comment]
HOLY SHIT HAHAHAHAHAHAHAAHAHAHAHAHAHAHA

**Comment by frontline03** [comment]
Regarding the theatre area being in space, that isn't an issue caused by me, that is also on the Metastation skyrat
image

**Comment by MrFagetti** [comment]
Why not remove the area then, if you haven't already? Making a change to the map and fixing a bug saves us time, right?

**Comment by frontline03** [comment]
I did

**Comment by MrFagetti** [comment]
image0 (47)

**Comment by MrFagetti** [comment]
image

I suggest moving the fire extinguisher or ATM to some other space, while from the east or west you won't see anything, for north you will see both the fire extinguisher and the ATM occupying the same area on the wall

image

Save yourself time and headaches with autonames, they easier to understand but the crux is that they charge by area they're placed in instead of area string var. Still very useful since said use case only matters on planet maps or occasionally radstorms.

image

Please use glass airlocks, for all that is holy, it's a stylistic thing but is generally accepted for a super-low security department with shitloads of glass like Botany/Hydroponics (and use dark tile under them for the sexy colorssss)

image

pls keep wiring fairly short, it's better that way. Not exactly your fault, however.

image

We serve food here sir.

image

I posit this abit more, to ground the airlock abit more and keep the table fairly consistent. Also, keep in mind the placement of extinguisher cabinets (I found one under the airlock lol), keeping them too close together mildly reduces the danger in fires and overall can just look a tad weird. Keep them about 1-3 depending on room size. Bar should have two, one behind the counter and another near an entryway.

image

I suggest clearing some of the null space by just making Cold Room beeg, cause why not?

image

Again, keeping the airlocks 'grounded' makes my brain feel more suspended in disbelief. Plus, I just prefer it this way, so that's me.

Just some suggestions I'd think I'd make from the file you posted. Otherwise, pretty decent stuff.

unknown (22)

**Pull request closed without merging**
