### PR TITLE
Omega rework

### PR DESCRIPTION
**Pull request by coldud13**
## About The Pull Request
All credit to Ciandestine for bringing omega up to date.

## Changelog
:cl: Ciandestine, coldud13
tweak: Omega rework
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
detective's office missing

**Comment by jjpark-kb** [comment]
ai upload still doesnt have turrets

**Comment by jjpark-kb** [comment]
blueshield office missing

**Comment by jjpark-kb** [comment]
camera at toxins testing center missing

**Comment by jjpark-kb** [comment]
can't tell, but it looks like both solars are missing wiring

**Comment by jjpark-kb** [comment]
missing xenoarch telepad

**Comment by jjpark-kb** [comment]
service is missing their autolathe

**Comment by jjpark-kb** [comment]
nanites are missing in science if you want that

**Comment by jjpark-kb** [comment]
circuit lab is missing if you want that

**Comment by jjpark-kb** [comment]
missing scrubber / inverted vent from toxins burn chamber

**Comment by jjpark-kb** [comment]
missing pda vendor at departures

**Comment by jjpark-kb** [comment]
missing posialert screen at robotics

**Comment by jjpark-kb** [comment]
place between rnd and the departures bathroom could be turned into maint rather than just open space

**Comment by jjpark-kb** [comment]
service protolathe should not be public

**Comment by jjpark-kb** [comment]
perhaps janitor could have shutters so they can have their office directly connected to the hallway, similar to robotics

**Comment by MrFagetti** [comment]
my toes really itch

**Pull request merged**
