### PR TITLE
Adds a Research Protolathe to the Ghost Cafe

### PR DESCRIPTION
**Pull request by faaaay**
Adds a Research Protolathe to the ghost cafe's nanite lab.

## About The Pull Request

Replaces one of the tables in the Ghost Cafe's Nanite Lab with a research protolathe (which replaced a box of nanite data disks, as these can be printed in the lathe.

This is my first PR via Github, I really hope I did this right.

## Why It's Good For The Game

This adds more ways for ghosts to spend their time and to use the cafe for experimentation. Isn't it weird to have the Cargo, Service and Sec lathes and no others?

## Changelog
:cl:
add: Research Protolathe in the Ghost Cafe Nanite Lab
del: A table with a box of Nanite Data Disks
tweak: Moved a nanite injector one tile to the west.

/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
you did not do it right, sorry.
You need to mapmerge or use strongdmm-- either or.

**Comment by faaaay** [comment]
> 
> 
> you did not do it right, sorry.
> You need to mapmerge or use strongdmm-- either or.

I understand, thank you. I'll look into how to do that.

**Comment by faaaay** [comment]
I've used StrongDMM to remake the file - is this alright?

**Comment by coldud13** [comment]
hmm travis still isn't happy about some other files for some reason, maybe try remaking this pr?
dunno why that happened tho

$ tools/travis/check_grep.sh
_maps/map_files/Deltastation/DeltaStation2.dmm:	pixel_x = 0;
_maps/map_files/Deltastation/DeltaStation2.dmm:	pixel_x = 0;
_maps/map_files/generic/CentCom_Skyrat.dmm:	pixel_x = 0;
_maps/map_files/generic/CentCom_Skyrat.dmm:	pixel_y = 0
_maps/map_files/MetaStation/MetaStation.dmm:	pixel_y = 0
_maps/map_files/OmegaStation/OmegaStation.dmm:	pixel_y = 0
_maps/map_files/OmegaStation/OmegaStation.dmm:	pixel_x = 0;
_maps/map_files/OmegaStation/OmegaStation_Lumos.dmm:	pixel_y = 0
_maps/map_files/OmegaStation/OmegaStation_Lumos.dmm:	pixel_x = 0;
_maps/map_files/OmegaStation/OmegaStation_Skyrat.dmm:	pixel_y = 0
_maps/map_files/OmegaStation/OmegaStation_Skyrat.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_x = 0;
_maps/map_files/Snaxi/Snaxi.dmm:	pixel_y = 0
_maps/RandomRuins/SpaceRuins/spacediner.dmm:	pixel_x = 0;
pixel_x/pixel_y = 0 variables detected in maps, please review to ensure they are not dirty varedits.

**Comment by jjpark-kb** [comment]
I would also like to mention that the original reason why a protolathe was not included was due to a possibility to influence the round from the cafe. If there is no issue there, then I see no issue with this PR (besides any travis errors)

**Comment by faaaay** [comment]
> hmm travis still isn't happy about some other files for some reason, maybe try remaking this pr?
> dunno why that happened tho

Sure, I'll try that!

> I would also like to mention that the original reason why a protolathe was not included was due to a possibility to influence the round from the cafe. If there is no issue there, then I see no issue with this PR (besides any travis errors)

That's a reasonable point. The only thing I can imagine _potentially_ being an issue is building a telecomms relay, but I'm personally not familiar enough to know if that would be possible or have any effect.

**Comment by faaaay** [comment]
https://github.com/Lumos-SS13/Lumos/pull/77

**Comment by coldud13** [comment]
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

**Pull request closed without merging**
