### PR TITLE
Snaxi Renovations

### PR DESCRIPTION
**Pull request by quackjack**
## About The Pull Request
This PR adds more maints to the station, expanding the overall size of each port. Virology in particular received a atmos maint akin to Pubby's. 
In addition, I gave the paramedic's room some love by expanding both it's space and facilities, making paramedic's actually want to bring patients there in a pinch, but not completely heal everything that could ail them. Their garage was outfitted with some tools as well, albeit basic stuff.
South port was where I focused most of my efforts since it was the least visited place on the station- yet everyone starts their round there if they are late. Past the blueshield's office and in front of the garden, i've added a construction area for engineers and with a maint connecting it to boot. Below the garden where the maint bar lies, i've added more maint deeper in.
Under engineering's secure storage, i've expanded the maint to have a door to the inside of the main engineering area, outside of the engine room. No flaps though.
Finally, I gave the dorms area an all new arcade room- with a whopping three arcade machines, new shutters, and that wacky arcade flooring. I've also added a basketball court just outside that, which was basically copied from the permabrig's court. Who says crew can't ball?

## Why It's Good For The Game
The main complaint I saw of Snaxi was that the maintenance area's were either too short or nonexistant. Meaning, stealthy antags would have it rough, and assistants that loved looting maint were bored to death. Also, many rooms that were present on other station just didn't exist here because of the space used. With these changes, I hope to make people enjoy playing on Snaxi more, instead of watching people die of boredom.

Screenshots available in the #snaxiiiii channel.

## Changelog
:cl:
add: Added more maint areas at: Fore Hall, Aft Maint 2, Port Hall, Port Bow Maint.
add: Added viro atmos room, construction area, arcade room, and basketball court.
/:cl:

### CODE REVIEW

**Comment by coldud13** [comment]
your dme seems a bit fucky, it's removing things from the dme?

**Comment by quackjack** [comment]
didn't touch that at all, is my code out of date or something?

**Comment by quackjack** [comment]
i noticed fagetti had the same stuff happen in code talk where he didnt touch the dme, yet shit was happening. is that the same here?

**Comment by coldud13** [comment]
alright cleaned up the branch so the funky dme stuff is gone, ill pop this into the testmerge

**Pull request merged**
