### PR TITLE
Removed Warden and Detective Private rooms

### PR DESCRIPTION
**Pull request by frontline03**
## About The Pull Request

Removes the bedroom and bathroom for warden and detective as they were unnecessary. adds some tools to help the warden also

## Why It's Good For The Game

Makes the office more compact and adds tools that can help him should the need arise

## Changelog
:cl:
del: Removed Wardens bedroom
del: Removed Wardens bathroom
del: Removed Detectives bedroom
add: Maint passage where the bedrooms where
add: Rack containing a mechanical toolbox, Cable coil and a multitool. 
/:cl:

### CODE REVIEW

**Comment by MrFagetti** [comment]
Metastation? More like Betastation, cause only TG beta cucks like this overrated map

unknown (22)

**Comment by frontline03** [comment]
Betalagstation.

**Comment by MrFagetti** [comment]
btw why does the Warden need a toolbox, cable coil, and multitool in his office? I'm all for removing redundant crap like private rooms (often only used for ERP), but something like a multitool is generally for engineers only, or the very adventurous assistant and/or sometimes used by Science/Robotics. Cables are kinda all-rounders cause making dedicated, powered structures are hard without the incredibly limited (hence coveted) insuls, and toolboxes are neither here or there, but for somebody like Warden maintaining prisoner pop, issuing equipment appropriate to alert level, and otherwise department-side administration, needed Engineer-access items and moreover an entire rack dedicated to them seems not only redundant but unnecessary. The entire purpose as I see it for not having everything available to everyone is exactly because generally certain items (namely the very useful in very powerful/gamechanging machinery multitool) are entrusted to those who are entrusted to use them. Just my two cents.

**Comment by frontline03** [comment]
I've two reasons. The first and weakest point is that it's filler for the empty space made. 
My second and better point is that the tools are useful in case of damage done to sec that engineering can't or won't fix (Due to inactivity or IC conflict) or to reinforce sec further such as adding barricades that need tools to dismantle in case of error. They were added so if they needed to do these thing, they would not have to leave sec to get the cable or the multitool. these tools, especially with the addition of synthetics, will also make repairing damaged synthetic that are in custody much easier than having to leave security to get cable, a welder or nanopaste.

**Comment by frontline03** [comment]
I should also point out that most wardens offices already have the blue toolbox, just no cable coil or multitool.

**Comment by MrFagetti** [comment]
I think above all the main issue is the multi-tool. Filling in null space is usually pretty easy, given that you can generally get away with adding something alot less secure like a small corner garden. Cables, like I said, are fine since they're not easy to just fuck around with unless you wanna roast yourself (usually because some atmo or engie decided to hotwire their hyper-trit 15 sm shard autism project into the powergrid)

**Comment by frontline03** [comment]
Honestly I wish we could just go back to the old sec layouts

**Comment by frontline03** [comment]
image

**Comment by MrFagetti** [comment]
Closing this because we've already merged a PR that effects Metastation's Security, henceforth making this stale and conflicting.

I can look into removing the private rooms, but I have other projects to focus on currently.

**Pull request closed without merging**
